# Generated by Django 5.2.3 on 2025-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("barcode", models.BigIntegerField(unique=True)),
            ],
        ),
    ]
